#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" @package docstring
Cronjob emailer script

Reads an HTML page from a Web server and sends it through email

@author Gabriele Tozzi <gabriele@tozzi.eu>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys

from optparse import OptionParser

import urllib

import smtplib
from email.Utils import COMMASPACE, formatdate, make_msgid
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class main:

    NAME = 'mailwww'
    VERSION = '0.2'

    def run(self):
        """ Main entry point principale """

        # Read command line
        usage = "%prog [opzioni] <url> <indirizzo> [<indirizzo2>] [<...>]"
        parser = OptionParser(usage=usage, version=self.NAME + ' ' + self.VERSION)
        parser.add_option("-s", "--smtp", dest="smtp",
            help="Indica l'smtp da usare. Default: localhost",
            default='localhost')
        parser.add_option("-u", "--smtp_user", dest="smtp_user",
            help="Indica il nome utente per l'autenticazione SMTP")
        parser.add_option("-p", "--smtp_pass", dest="smtp_pass",
            help="Indica la password per l'autenticazione SMTP")
        parser.add_option("-c", "--cc", dest="cc",
            help="Eventuale destinatario in copia")
        parser.add_option("-f", "--from", dest="sender",
            help="Mittente della mail. Default: emailer@localhost",
            default="emailer@localhost")
        parser.add_option("-j", "--subject", dest="subject",
            help="Oggetto della mail. Default: Autogenerated Mail",
            default="Autogenerated Mail")

        (options, args) = parser.parse_args()
        
        # Parse mandatory arguments
        if len(args) < 2:
            parser.error("numero di argomenti non valido")
        dest = []
        i = 0
        for a in args:
            if i == 0:
                url = a
            else:
                dest.append(a)
            i += 1

        # Parse optional arguments
        cc = []
        if options.cc:
            cc.append(options.cc)
        host = options.smtp
        port = 25
        user = options.smtp_user
        pwd = options.smtp_pass
        sender = options.sender
        subject = options.subject

        # Opens URL
        f = urllib.urlopen(url)
        html = f.read()
        
        # Prepare mail
        msg = MIMEMultipart()
        msg['Date'] = formatdate(localtime=True)
        msg['Message-ID'] = make_msgid('emailer')
        msg['Subject'] = subject
        msg['From'] = sender
        msg['To'] = ', '.join(dest)
        if cc:
            msg['Cc'] = ', '.join(cc)
        msg.preamble = 'This is a milti-part message in MIME format.'
        
        txt = MIMEText(html.encode('utf-8'), 'html', 'utf-8')
        msg.attach(txt)
        
        # Sends message
        smtp = smtplib.SMTP()
        smtp.connect(host, port)
        if user:
            smtp.login(user, pwd)
        smtp.sendmail(sender, dest+cc, msg.as_string())
        smtp.quit()

if __name__ == '__main__':
    app = main()
    app.run()
    sys.exit(0)
